services:
  database:
    build: ./database
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass redis
    ports:
     - 6379:6379
